# Generated by Django 4.1.2 on 2022-10-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_articlemodel_codemodel_rename_apimodel_formmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('url_image', models.URLField(max_length=500)),
                ('generating_date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='url_image',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='article',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
