# Generated by Django 4.1.2 on 2022-11-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_articlemodel_user_codemodel_user_imagemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='generating_date',
            field=models.DateTimeField(null=True),
        ),
    ]
