# Generated by Django 4.1.2 on 2022-11-02 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_imagemodel_generating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='generating_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='codemodel',
            name='generating_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='generating_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
