# Generated by Django 4.1.2 on 2022-11-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_articlemodel_generating_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormModel',
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='codemodel',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
